---

- name: Add Grafana APT key
  ansible.builtin.shell:
    cmd: wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/grafana.gpg > /dev/null

- name: Add Grafana APT repository
  ansible.builtin.shell:
    cmd: echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main" | sudo tee /etc/apt/sources.list.d/grafana.list

- name: Install Grafana version {{grafana_version}}
  ansible.builtin.apt:
    name: grafana={{ grafana_version }}
    update_cache: yes

- name: Launch Grafana service
  ansible.builtin.systemd_service:
    name: grafana-server
    enabled: true
    daemon_reload: true
    state: started

- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    update_cache: yes

- name: Allow port 3000
  community.general.ufw:
    rule: allow
    port: 3000
    proto: tcp
