---
- name: Create data folder
  ansible.builtin.file:
    path: "{{data_folder}}"
    state: directory
    mode: '0755'

- name: Place data_collector.py
  ansible.builtin.template:
    src: data_collector.py.j2
    dest: "{{base_install_dir}}/data_collector.py"

- name: Place data_collector service file
  ansible.builtin.template:
    src: data_collector.service.j2
    dest: /etc/systemd/system/data_collector.service

- name: Create and launch data_collector service
  ansible.builtin.systemd_service:
    name: data_collector
    enabled: true
    daemon_reload: true
    state: started
