---
- name: Place web.py
  ansible.builtin.template:
    src: web.py.j2
    dest: "{{base_install_dir}}/web.py"

- name: Place web service file
  ansible.builtin.template:
    src: web.service.j2
    dest: /etc/systemd/system/web.service

- name: Create and launch web service
  ansible.builtin.systemd_service:
    name: web
    enabled: true
    daemon_reload: true
    state: started
